---
name: luarocks upload
on:
  push:
    tags:
      - 'v*'
  pull_request: # Will test packaging without publishing on PR
  workflow_dispatch: # Allow manual trigger

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: luarocks upload
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Luarocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          name: fzy
          summary: "A lua implementation of the fzy fuzzy matching algorithm"
          detailed_description: |
            A Lua port of fzy's fuzzy string matching algorithm.
            This includes both a pure Lua implementation and a compiled C implementation with a Lua wrapper.
            fzy tries to find the result the user wants by favoring consecutive
            matches, and matches at the beginnings of words.
          copy_directories: |
            docs
          test_interpreters: "lua"
          template: ".github/workflows/rockspec.template"
